### ISSUE TITLE
create wireguard communication 

### ISSUE THREAD

**Issue by mrtrkmn** [aau-network-security/defatt#3]
Wireguard will be placed into architecture, try to run wireguard in docker container by providing some configuration with routed ip table rules. IP table rules should be dynamically generated with name of communications (vlans) on openvswitch.

The issue could be divided into sub tasks as follows:

- [x] Generate a template for IPTables rule to dynamically provide interface names in config (opened in another issue #8 )
- [x] Place some VMs on vlans provided on IPTables (pull request created #7 ) 
- [x] Create a connection to VM console in order to ping other hosts in vlan(opened in another issue #9 )
- [x] Run wireguard docker container with customized wireguard configuration. (opened in another issue #10)
- [x] Try to access VM by connecting to wireguard. (opened in another issue #11 )
